

using Ferrite, FerriteGmsh
...
grid = togrid(logo_mesh)
...
ip = Lagrange{RefTriangle,1}()^dim
...
cellvalues = CellValues(qr, ip)
...
facetvalues = FacetValues(...)
...
C = gradient(...)
...
assemble_cell!/assemble_global!
...
assemble_external_forces!
...


using FerriteShells, FerriteGmsh
...
grid = shell_grid(togrid(logo_mesh))
...
ip = Lagrange{RefTriangle,1}()
...
scv = ShellCellValues(qr, ip, ip)
...
# (not needed)
...
mat = LinearElastic(Emod, ν, thickness)
...
membrane_tangent_RM!/bending_tangent_RM!
membrane_residuals_RM!/bending_residuals_RM! via shelldofs(cell)
...
assemble_traction!(f_ext, dh, facetset, ip, fqr, traction)
...